apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-core-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://host.minikube.internal:5432/iris
  SPRING_KAFKA_BOOTSTRAP_SERVERS: host.minikube.internal:29093
  SPRING_DATA_MONGODB_URI: mongodb://host.minikube.internal:27017/trading_core
  REDIS_HOST: host.minikube.internal
  REDIS_PORT: "6379"
  MANAGEMENT_OTLP_TRACING_ENDPOINT: http://host.minikube.internal:4318/v1/traces
  LOKI_URL: http://host.minikube.internal:3100
  COOKIE_SECURE: "false"